// // pakistanLocations.js
// export const pakistanLocations = {
//     Punjab: ['Attock', 'Bahawalnagar', 'Bahawalpur', 'Bhakkar', 'Chakwal', 'Chiniot', 'Dera Ghazi Khan', 'Faisalabad', 'Gujranwala', 'Gujrat', 'Hafizabad', 'Jhang', 'Jhelum', 'Kasur', 'Khanewal', 'Khushab', 'Lahore', 'Layyah', 'Lodhran', 'Mandi Bahauddin', 'Mianwali', 'Multan', 'Muzaffargarh', 'Nankana Sahib', 'Narowal', 'Okara', 'Pakpattan', 'Rahim Yar Khan', 'Rajanpur', 'Rawalpindi', 'Sahiwal', 'Sargodha', 'Sheikhupura', 'Sialkot', 'Toba Tek Singh', 'Vehari'],
//     Sindh: ['Badin', 'Dadu', 'Ghotki', 'Hyderabad', 'Jacobabad', 'Jamshoro', 'Karachi Central', 'Karachi East', 'Karachi South', 'Karachi West', 'Korangi', 'Keamari', 'Kashmore', 'Khairpur', 'Larkana', 'Matiari', 'Mirpurkhas', 'Naushahro Feroze', 'Qambar Shahdadkot', 'Sanghar', 'Shaheed Benazirabad', 'Shikarpur', 'Sukkur', 'Tando Allahyar', 'Tando Muhammad Khan', 'Tharparkar', 'Thatta', 'Umerkot'],
//     Balochistan: ['Awaran', 'Barkhan', 'Chagai', 'Dera Bugti', 'Gwadar', 'Harnai', 'Jafarabad', 'Jhal Magsi', 'Kacchi', 'Kalat', 'Kech', 'Kharan', 'Khuzdar', 'Killa Abdullah', 'Killa Saifullah', 'Kohlu', 'Lasbela', 'Lehri', 'Loralai', 'Mastung', 'Musakhel', 'Nasirabad', 'Nushki', 'Panjgur', 'Pishin', 'Quetta', 'Sherani', 'Sibi', 'Sohbatpur', 'Washuk', 'Zhob', 'Ziarat'],
//     KhyberPakhtunkhwa: ['Abbottabad', 'Bajaur', 'Bannu', 'Batagram', 'Buner', 'Charsadda', 'Chitral Lower', 'Chitral Upper', 'Dera Ismail Khan', 'Hangu', 'Haripur', 'Karak', 'Khyber', 'Kohat', 'Kohistan Lower', 'Kohistan Upper', 'Kurram', 'Lakki Marwat', 'Malakand', 'Mansehra', 'Mardan', 'Mohmand', 'Nowshera', 'Orakzai', 'Peshawar', 'Shangla', 'South Waziristan', 'Swabi', 'Swat', 'Tank', 'Torghar', 'Upper Dir', 'Lower Dir'],
//     GilgitBaltistan: ['Astore', 'Diamer', 'Ghanche', 'Ghizer', 'Gilgit', 'Hunza', 'Kharmang', 'Nagar', 'Shigar', 'Skardu'],
//     AzadKashmir: ['Bagh', 'Bhimber', 'Hattian Bala', 'Haveli', 'Kotli', 'Mirpur', 'Muzaffarabad', 'Neelum', 'Poonch', 'Sudhnoti'],
//     Islamabad: ['Islamabad']
// };


export const pakistanLocations = {
    Punjab: {
        'Attock': ['Attock City', 'Hazro', 'Fateh Jang'],
        'Bahawalnagar': ['Bahawalnagar City', 'Chishtian', 'Haroonabad'],
        'Bahawalpur': ['Bahawalpur City', 'Ahmadpur East', 'Khairpur Tamewali'],
        'Bhakkar': ['Bhakkar City', 'Darya Khan', 'Kallur Kot'],
        'Chakwal': ['Chakwal City', 'Choa Saidan Shah', 'Kallar Kahar'],
        'Chiniot': ['Chiniot City', 'Bhawana', 'Lalian'],
        'Dera Ghazi Khan': ['Dera Ghazi Khan City', 'Taunsa', 'Kot Chutta'],
        'Faisalabad': ['Madina Town', 'Jinnah Town', 'Lyallpur Town'],
        'Gujranwala': ['Gujranwala City', 'Ali Pur Chattha', 'Nandi Pur'],
        'Gujrat': ['Gujrat City', 'Kunjah', 'Sarai Alamgir'],
        'Hafizabad': ['Hafizabad City', 'Pindi Bhattian', 'Jalalpur Bhattian'],
        'Jhang': ['Jhang City', 'Ahmadpur Sial', 'Shorkot'],
        'Jhelum': ['Jhelum City', 'Dina', 'Pind Dadan Khan'],
        'Kasur': ['Kasur City', 'Pattoki', 'Chunian'],
        'Khanewal': ['Khanewal City', 'Mian Channu', 'Kabirwala'],
        'Khushab': ['Khushab City', 'Noorpur Thal', 'Quaidabad'],
        'Lahore': ['Model Town', 'Johar Town', 'Iqbal Town'],
        'Layyah': ['Layyah City', 'Chobara', 'Karor Lal Esan'],
        'Lodhran': ['Lodhran City', 'Dunyapur', 'Kahror Pacca'],
        'Mandi Bahauddin': ['Mandi Bahauddin City', 'Phalia', 'Malakwal'],
        'Mianwali': ['Mianwali City', 'Isa Khel', 'Kalabagh'],
        'Multan': ['Multan City', 'Shujabad', 'Jalalpur Pirwala'],
        'Muzaffargarh': ['Muzaffargarh City', 'Alipur', 'Jatoi'],
        'Nankana Sahib': ['Nankana Sahib City', 'Sangla Hill', 'Shahkot'],
        'Narowal': ['Narowal City', 'Shakargarh', 'Zafarwal'],
        'Okara': ['Okara City', 'Renala Khurd', 'Depalpur'],
        'Pakpattan': ['Pakpattan City', 'Arifwala', 'Burewala'],
        'Rahim Yar Khan': ['Rahim Yar Khan City', 'Khanpur', 'Sadiqabad'],
        'Rajanpur': ['Rajanpur City', 'Jampur', 'Rojhan'],
        'Rawalpindi': ['Rawalpindi City', 'Taxila', 'Gujar Khan'],
        'Sahiwal': ['Sahiwal City', 'Chichawatni', 'Harappa'],
        'Sargodha': ['Sargodha City', 'Bhalwal', 'Sillanwali'],
        'Sheikhupura': ['Sheikhupura City', 'Ferozewala', 'Muridke'],
        'Sialkot': ['Sialkot City', 'Daska', 'Pasrur'],
        'Toba Tek Singh': ['Toba Tek Singh City', 'Gojra', 'Kamalia'],
        'Vehari': ['Vehari City', 'Burewala', 'Mailsi']
    },
    Sindh: {
        'Badin': ['Badin City', 'Talhar', 'Matli'],
        'Dadu': ['Dadu City', 'Johi', 'Khairpur Nathan Shah'],
        'Ghotki': ['Ghotki City', 'Mirpur Mathelo', 'Daharki'],
        'Hyderabad': ['Hyderabad City', 'Latifabad', 'Qasimabad'],
        'Jacobabad': ['Jacobabad City', 'Garhi Khairo', 'Thul'],
        'Jamshoro': ['Jamshoro City', 'Sehwan', 'Kotri'],
        'Karachi Central': ['Nazimabad', 'Liaquatabad', 'Gulberg'],
        'Karachi East': ['Gulshan-e-Iqbal', 'Johar', 'Ferozabad'],
        'Karachi South': ['Clifton', 'Defence', 'Saddar'],
        'Karachi West': ['Orangi', 'Baldia', 'SITE'],
        'Korangi': ['Korangi', 'Landhi', 'Shah Faisal'],
        'Keamari': ['Keamari', 'Mauripur', 'Shershah'],
        'Kashmore': ['Kashmore City', 'Kandhkot', 'Tangwani'],
        'Khairpur': ['Khairpur City', 'Kingri', 'Faqirwali'],
        'Larkana': ['Larkana City', 'Ratodero', 'Dokri'],
        'Matiari': ['Matiari City', 'Hala', 'Saeedabad'],
        'Mirpurkhas': ['Mirpurkhas City', 'Digri', 'Kot Ghulam Muhammad'],
        'Naushahro Feroze': ['Naushahro Feroze City', 'Moro', 'Bhiria'],
        'Qambar Shahdadkot': ['Qambar', 'Shahdadkot', 'Miro Khan'],
        'Sanghar': ['Sanghar City', 'Shahdadpur', 'Tando Adam'],
        'Shaheed Benazirabad': ['Nawabshah', 'Daulatpur', 'Qazi Ahmad'],
        'Shikarpur': ['Shikarpur City', 'Garhi Yasin', 'Lakhi'],
        'Sukkur': ['Sukkur City', 'Rohri', 'Pano Aqil'],
        'Tando Allahyar': ['Tando Allahyar City', 'Chambar', 'Jhando Mari'],
        'Tando Muhammad Khan': ['Tando Muhammad Khan City', 'Bulri Shah Karim', 'Khipro'],
        'Tharparkar': ['Mithi', 'Islamkot', 'Diplo'],
        'Thatta': ['Thatta City', 'Mirpur Sakro', 'Keti Bandar'],
        'Umerkot': ['Umerkot City', 'Pithoro', 'Samaro']
    },
    Balochistan: {
        'Awaran': ['Awaran City', 'Jhal Jao', 'Gishkaur'],
        'Barkhan': ['Barkhan City', 'Duki', 'Rakhni'],
        'Chagai': ['Dalbandin', 'Nok Kundi', 'Taftan'],
        'Dera Bugti': ['Dera Bugti City', 'Sui', 'Phelawagh'],
        'Gwadar': ['Gwadar City', 'Pasni', 'Ormara'],
        'Harnai': ['Harnai City', 'Khost', 'Shahrag'],
        'Jafarabad': ['Dera Allah Yar', 'Gandakha', 'Usta Muhammad'],
        'Jhal Magsi': ['Jhal Magsi City', 'Gandawa', 'Rindak'],
        'Kacchi': ['Dhadar', 'Mach', 'Sanni'],
        'Kalat': ['Kalat City', 'Manguchar', 'Surab'],
        'Kech': ['Turbat', 'Mand', 'Tump'],
        'Kharan': ['Kharan City', 'Nushki', 'Nag'],
        'Khuzdar': ['Khuzdar City', 'Wadh', 'Zehrat'],
        'Killa Abdullah': ['Chaman', 'Gulistan', 'Dobandi'],
        'Killa Saifullah': ['Killa Saifullah City', 'Muslim Bagh', 'Badini'],
        'Kohlu': ['Kohlu City', 'Mawand', 'Kahan'],
        'Lasbela': ['Uthal', 'Bela', 'Liari'],
        'Lehri': ['Lehri City', 'Kambri', 'Dhadar'],
        'Loralai': ['Loralai City', 'Bori', 'Duki'],
        'Mastung': ['Mastung City', 'Dasht', 'Khad Kocha'],
        'Musakhel': ['Musakhel City', 'Kingri', 'Drazinda'],
        'Nasirabad': ['Dera Murad Jamali', 'Tamboo', 'Chatter'],
        'Nushki': ['Nushki City', 'Taftan', 'Dalbandin'],
        'Panjgur': ['Panjgur City', 'Gichk', 'Paroom'],
        'Pishin': ['Pishin City', 'Karezat', 'Barshore'],
        'Quetta': ['Quetta City', 'Hanna Valley', 'Kuchlak'],
        'Sherani': ['Sherani City', 'Zhob', 'Kingri'],
        'Sibi': ['Sibi City', 'Lehri', 'Kohlu'],
        'Sohbatpur': ['Sohbatpur City', 'Dera Allah Yar', 'Gandakha'],
        'Washuk': ['Washuk City', 'Besima', 'Kharan'],
        'Zhob': ['Zhob City', 'Qamar Din Karez', 'Killa Saifullah'],
        'Ziarat': ['Ziarat City', 'Sanjawi', 'Sinjawi']
    },
    KhyberPakhtunkhwa: {
        'Abbottabad': ['Abbottabad City', 'Nathiagali', 'Havelian'],
        'Bajaur': ['Khar', 'Nawagai', 'Mamund'],
        'Bannu': ['Bannu City', 'Domel', 'Kakki'],
        'Batagram': ['Batagram City', 'Allai', 'Banna'],
        'Buner': ['Daggar', 'Gadezai', 'Chagharzai'],
        'Charsadda': ['Charsadda City', 'Tangi', 'Shabqadar'],
        'Chitral Lower': ['Chitral City', 'Drosh', 'Astore'],
        'Chitral Upper': ['Mastuj', 'Booni', 'Torkhow'],
        'Dera Ismail Khan': ['Dera Ismail Khan City', 'Paharpur', 'Paroa'],
        'Hangu': ['Hangu City', 'Tall', 'Doaba'],
        'Haripur': ['Haripur City', 'Khanpur', 'Ghazi'],
        'Karak': ['Karak City', 'Takht-e-Nasrati', 'Banda Daud Shah'],
        'Khyber': ['Landi Kotal', 'Jamrud', 'Bara'],
        'Kohat': ['Kohat City', 'Lachi', 'Gumbat'],
        'Kohistan Lower': ['Pattan', 'Palas', 'Kandia'],
        'Kohistan Upper': ['Dasu', 'Kandia', 'Pattan'],
        'Kurram': ['Parachinar', 'Ali Zai', 'Peiwar'],
        'Lakki Marwat': ['Lakki Marwat City', 'Naurang', 'Tajori'],
        'Malakand': ['Dargai', 'Batkhela', 'Chakdara'],
        'Mansehra': ['Mansehra City', 'Baffa', 'Oghi'],
        'Mardan': ['Mardan City', 'Takht Bhai', 'Katlang'],
        'Mohmand': ['Ghalanai', 'Pindiali', 'Lakaro'],
        'Nowshera': ['Nowshera City', 'Jehangira', 'Pabbi'],
        'Orakzai': ['Kalaya', 'Upper Orakzai', 'Lower Orakzai'],
        'Peshawar': ['Peshawar City', 'Hayatabad', 'University Town'],
        'Shangla': ['Alpuri', 'Besham', 'Chakesar'],
        'South Waziristan': ['Wana', 'Ladha', 'Sarwakai'],
        'Swabi': ['Swabi City', 'Topi', 'Lahor'],
        'Swat': ['Mingora', 'Saidu Sharif', 'Matta'],
        'Tank': ['Tank City', 'Jandola', 'Gomal'],
        'Torghar': ['Judba', 'Kand', 'Kuz Kana'],
        'Upper Dir': ['Dir City', 'Wari', 'Kumrat'],
        'Lower Dir': ['Timergara', 'Khall', 'Munda']
    },
    GilgitBaltistan: {
        'Astore': ['Astore City', 'Chilam', 'Shonter'],
        'Diamer': ['Chilas', 'Darel', 'Tangir'],
        'Ghanche': ['Khaplu', 'Mashabrum', 'Daghoni'],
        'Ghizer': ['Gahkuch', 'Ishkoman', 'Punial'],
        'Gilgit': ['Gilgit City', 'Jutial', 'Danyore'],
        'Hunza': ['Karimabad', 'Aliabad', 'Ganish'],
        'Kharmang': ['Kharmang City', 'Tolti', 'Masho'],
        'Nagar': ['Nagar City', 'Chalt', 'Hopar'],
        'Shigar': ['Shigar City', 'Askole', 'Hushe'],
        'Skardu': ['Skardu City', 'Kachura', 'Shigar']
    },
    AzadKashmir: {
        'Bagh': ['Bagh City', 'Dhari', 'Hari Ghel'],
        'Bhimber': ['Bhimber City', 'Samahni', 'Barnala'],
        'Hattian Bala': ['Hattian Bala City', 'Chikkar', 'Leepa'],
        'Haveli': ['Forward Kahuta', 'Khurshidabad', 'Kotla'],
        'Kotli': ['Kotli City', 'Khuiratta', 'Fatehpur Thakiala'],
        'Mirpur': ['Mirpur City', 'Dadyal', 'Chaksawari'],
        'Muzaffarabad': ['Muzaffarabad City', 'Pattika', 'Garhi Dupatta'],
        'Neelum': ['Athmuqam', 'Sharda', 'Taobat'],
        'Poonch': ['Rawalakot', 'Hajira', 'Thorar'],
        'Sudhnoti': ['Pallandri', 'Mang', 'Trar Dewan']
    },
    Islamabad: {
        'Islamabad': ['F-7', 'G-9', 'E-11']
    }
};